In [6]:
import os
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

In [7]:
import warnings
warnings.filterwarnings("ignore")

1. membaca data set hepatitis

In [8]:
## Read "hepatitis.csv" using pandas
# target =  1: Die; 2: Live 
hepatitis_data = pd.read_csv("hepatitis.csv", na_values="?")

In [9]:
hepatitis_data.shape

(155, 21)

In [10]:
hepatitis_data.head()

ID  target  age  gender  steroid  antivirals  fatigue  malaise  anorexia  \
0   1       2   30       2      1.0           2      2.0      2.0       2.0   
1   2       2   50       1      1.0           2      1.0      2.0       2.0   
2   3       2   78       1      2.0           2      1.0      2.0       2.0   
3   4       2   31       1      NaN           1      2.0      2.0       2.0   
4   5       2   34       1      2.0           2      2.0      2.0       2.0   

   liverBig  ...  spleen  spiders  ascites  varices  bili    alk   sgot  albu  \
0       1.0  ...     2.0      2.0      2.0      2.0   1.0   85.0   18.0   4.0   
1       1.0  ...     2.0      2.0      2.0      2.0   0.9  135.0   42.0   3.5   
2       2.0  ...     2.0      2.0      2.0      2.0   0.7   96.0   32.0   4.0   
3       2.0  ...     2.0      2.0      2.0      2.0   0.7   46.0   52.0   4.0   
4       2.0  ...     2.0      2.0      2.0      2.0   1.0    NaN  200.0   4.0   

   protime  histology  
0      NaN          1  
1      NaN          1  
2      NaN          1  
3     80.0          1  
4      NaN          1  

[5 rows x 21 columns]

2. Memeriksa statistik ringkasan dasar dari data

In [11]:
hepatitis_data.describe()

ID      target         age      gender     steroid  antivirals  \
count  155.000000  155.000000  155.000000  155.000000  154.000000  155.000000   
mean    78.000000    1.793548   41.200000    1.103226    1.506494    1.845161   
std     44.888751    0.406070   12.565878    0.305240    0.501589    0.362923   
min      1.000000    1.000000    7.000000    1.000000    1.000000    1.000000   
25%     39.500000    2.000000   32.000000    1.000000    1.000000    2.000000   
50%     78.000000    2.000000   39.000000    1.000000    2.000000    2.000000   
75%    116.500000    2.000000   50.000000    1.000000    2.000000    2.000000   
max    155.000000    2.000000   78.000000    2.000000    2.000000    2.000000   

          fatigue     malaise    anorexia    liverBig  ...     spleen  \
count  154.000000  154.000000  154.000000  145.000000  ...  150.00000   
mean     1.350649    1.603896    1.792208    1.827586  ...    1.80000   
std      0.478730    0.490682    0.407051    0.379049  ...    0.40134   
min      1.000000    1.000000    1.000000    1.000000  ...    1.00000   
25%      1.000000    1.000000    2.000000    2.000000  ...    2.00000   
50%      1.000000    2.000000    2.000000    2.000000  ...    2.00000   
75%      2.000000    2.000000    2.000000    2.000000  ...    2.00000   
max      2.000000    2.000000    2.000000    2.000000  ...    2.00000   

          spiders     ascites    varices        bili         alk       sgot  \
count  150.000000  150.000000  150.00000  149.000000  126.000000  151.00000   
mean     1.660000    1.866667    1.88000    1.427517  105.325397   85.89404   
std      0.475296    0.341073    0.32605    1.212149   51.508109   89.65089   
min      1.000000    1.000000    1.00000    0.300000   26.000000   14.00000   
25%      1.000000    2.000000    2.00000    0.700000   74.250000   31.50000   
50%      2.000000    2.000000    2.00000    1.000000   85.000000   58.00000   
75%      2.000000    2.000000    2.00000    1.500000  132.250000  100.50000   
max      2.000000    2.000000    2.00000    8.000000  295.000000  648.00000   

             albu     protime   histology  
count  139.000000   88.000000  155.000000  
mean     3.817266   61.852273    1.451613  
std      0.651523   22.875244    0.499266  
min      2.100000    0.000000    1.000000  
25%      3.400000   46.000000    1.000000  
50%      4.000000   61.000000    1.000000  
75%      4.200000   76.250000    2.000000  
max      6.400000  100.000000    2.000000  

[8 rows x 21 columns]

3.Check for value counts in target variabel

In [12]:
hepatitis_data.target.value_counts()

target
2    123
1     32
Name: count, dtype: int64

4.Periksa tipe data setiap variabel

In [13]:
hepatitis_data.dtypes

ID              int64
target          int64
age             int64
gender          int64
steroid       float64
antivirals      int64
fatigue       float64
malaise       float64
anorexia      float64
liverBig      float64
liverFirm     float64
spleen        float64
spiders       float64
ascites       float64
varices       float64
bili          float64
alk           float64
sgot          float64
albu          float64
protime       float64
histology       int64
dtype: object

In [14]:
cat_cols = hepatitis_data.columns[hepatitis_data.nunique() < 5]

In [15]:
num_cols = hepatitis_data.columns[hepatitis_data.nunique() >= 5]

5. hapus kolom yang tidak signifikan

In [16]:
hepatitis_data.drop(["ID"], axis = 1, inplace=True)
num_cols = hepatitis_data.columns[hepatitis_data.nunique() >= 5]

In [17]:
hepatitis_data.head()

target  age  gender  steroid  antivirals  fatigue  malaise  anorexia  \
0       2   30       2      1.0           2      2.0      2.0       2.0   
1       2   50       1      1.0           2      1.0      2.0       2.0   
2       2   78       1      2.0           2      1.0      2.0       2.0   
3       2   31       1      NaN           1      2.0      2.0       2.0   
4       2   34       1      2.0           2      2.0      2.0       2.0   

   liverBig  liverFirm  spleen  spiders  ascites  varices  bili    alk   sgot  \
0       1.0        2.0     2.0      2.0      2.0      2.0   1.0   85.0   18.0   
1       1.0        2.0     2.0      2.0      2.0      2.0   0.9  135.0   42.0   
2       2.0        2.0     2.0      2.0      2.0      2.0   0.7   96.0   32.0   
3       2.0        2.0     2.0      2.0      2.0      2.0   0.7   46.0   52.0   
4       2.0        2.0     2.0      2.0      2.0      2.0   1.0    NaN  200.0   

   albu  protime  histology  
0   4.0      NaN          1  
1   3.5      NaN          1  
2   4.0      NaN          1  
3   4.0     80.0          1  
4   4.0      NaN          1

6. Identifikasi Kolom Kategorikal dan simpan dalam variabel cat_cols dan numerik ke dalam num_cols

In [18]:
num_cols = ["age", "bili", "alk", "sgot", "albu", "protime"]
cat_cols = ['gender', 'steroid', 'antivirals', 'fatigue', 'malaise', 'anorexia', 'liverBig', 
            'liverFirm', 'spleen', 'spiders', 'ascites', 'varices', 'histology']

1. memeriksa nilai nol 

In [19]:
hepatitis_data.isna().sum()

target         0
age            0
gender         0
steroid        1
antivirals     0
fatigue        1
malaise        1
anorexia       1
liverBig      10
liverFirm     11
spleen         5
spiders        5
ascites        5
varices        5
bili           6
alk           29
sgot           4
albu          16
protime       67
histology      0
dtype: int64

In [20]:
hepatitis_data.isnull().sum()

target         0
age            0
gender         0
steroid        1
antivirals     0
fatigue        1
malaise        1
anorexia       1
liverBig      10
liverFirm     11
spleen         5
spiders        5
ascites        5
varices        5
bili           6
alk           29
sgot           4
albu          16
protime       67
histology      0
dtype: int64

8. Membagi data menjadi X dan y

In [21]:
X = hepatitis_data.drop(["target"], axis = 1)

In [22]:
y = hepatitis_data["target"]

In [23]:
print(X.shape, y.shape)

(155, 19) (155,)


9. Pisahkan data menjadi X_train, X_test, y_train, y_test dengan test_size = 0.20 menggunakan sklearn

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 123)

In [25]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 123)
## Print the shape of X_train, X_test, y_train, y_test
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(124, 19)
(31, 19)
(124,)
(31,)


10. periksa nilai null pada train dan test, periksa value_count pada y_train dan y_test

In [26]:
print(y_train.value_counts()/X_train.shape[0])


target
2    0.790323
1    0.209677
Name: count, dtype: float64


In [27]:
print(y_train.value_counts()/X_train.shape[0])

target
2    0.790323
1    0.209677
Name: count, dtype: float64


In [28]:
#nilai null data trin
X_train.isna().sum()

age            0
gender         0
steroid        1
antivirals     0
fatigue        1
malaise        1
anorexia       1
liverBig       7
liverFirm      8
spleen         4
spiders        4
ascites        4
varices        4
bili           6
alk           23
sgot           4
albu          13
protime       53
histology      0
dtype: int64

In [29]:
#nilai null data test
X_test.isna().sum()

age            0
gender         0
steroid        0
antivirals     0
fatigue        0
malaise        0
anorexia       0
liverBig       3
liverFirm      3
spleen         1
spiders        1
ascites        1
varices        1
bili           0
alk            6
sgot           0
albu           3
protime       14
histology      0
dtype: int64

11. Menghitung Kolom Kategorikal dengan modus dan kolom Numerik dengan rata-rata


In [30]:
df_cat_train = X_train[cat_cols]
df_cat_test = X_test[cat_cols]

In [31]:
# Impute on train
# df_cat_train = df_cat_train.fillna(df_cat_train.mode().iloc[0])

# Impute on test
# df_cat_test = df_cat_test.fillna(df_cat_train.mode().iloc[0])

In [32]:
from sklearn.impute import SimpleImputer
cat_imputer = SimpleImputer(strategy='most_frequent')
cat_imputer.fit(df_cat_train)

SimpleImputer(strategy='most_frequent')

In [33]:
df_cat_train = pd.DataFrame(cat_imputer.transform(df_cat_train), columns=cat_cols)

In [34]:
df_cat_test = pd.DataFrame(cat_imputer.transform(df_cat_test), columns=cat_cols)

In [35]:
df_num_train = X_train[num_cols]
df_num_test = X_test[num_cols]

In [36]:
# Impute on train
# df_num_train = df_num_train.fillna(df_num_train.mean())

#Impute on test
# df_num_test = df_num_test.fillna(df_num_train.mean())

In [37]:
num_imputer = SimpleImputer(strategy='median')
num_imputer.fit(df_num_train[num_cols])

SimpleImputer(strategy='median')

In [38]:
df_num_train = pd.DataFrame ( num_imputer.transform(df_num_train), columns= num_cols)

In [39]:
df_num_test =  pd.DataFrame(num_imputer.transform(df_num_test), columns=num_cols)

In [40]:
# Combine numeric and categorical in train
X_train = pd.concat([df_num_train, df_cat_train], axis = 1)

# Combine numeric and categorical in test
X_test = pd.concat([df_num_test, df_cat_test], axis = 1)

In [41]:
X_train.isna().sum()

age           0
bili          0
alk           0
sgot          0
albu          0
protime       0
gender        0
steroid       0
antivirals    0
fatigue       0
malaise       0
anorexia      0
liverBig      0
liverFirm     0
spleen        0
spiders       0
ascites       0
varices       0
histology     0
dtype: int64

In [42]:
X_test.isna().sum()

age           0
bili          0
alk           0
sgot          0
albu          0
protime       0
gender        0
steroid       0
antivirals    0
fatigue       0
malaise       0
anorexia      0
liverBig      0
liverFirm     0
spleen        0
spiders       0
ascites       0
varices       0
histology     0
dtype: int64

Mengonversi semua kolom kategorikal ke Format Bilangan Bulat sebelum dummifikasi (2,0 sebagai 2, dst.)

In [43]:
# Train
X_train[cat_cols] = X_train[cat_cols].astype('int')

# Test
X_test[cat_cols] = X_test[cat_cols].astype('int')

12. mengecilkan kolom katergorikal

In [44]:
## Convert Categorical Columns to Dummies
# Train
X_train = pd.get_dummies(X_train, columns=cat_cols, drop_first=True)

# Test
X_test = pd.get_dummies(X_test, columns=cat_cols, drop_first=True)

In [45]:
X_train.columns

Index(['age', 'bili', 'alk', 'sgot', 'albu', 'protime', 'gender_2',
       'steroid_2', 'antivirals_2', 'fatigue_2', 'malaise_2', 'anorexia_2',
       'liverBig_2', 'liverFirm_2', 'spleen_2', 'spiders_2', 'ascites_2',
       'varices_2', 'histology_2'],
      dtype='object')

In [46]:
X_test.columns

Index(['age', 'bili', 'alk', 'sgot', 'albu', 'protime', 'gender_2',
       'steroid_2', 'antivirals_2', 'fatigue_2', 'malaise_2', 'anorexia_2',
       'liverBig_2', 'liverFirm_2', 'spleen_2', 'spiders_2', 'ascites_2',
       'varices_2', 'histology_2'],
      dtype='object')

13.Scale the numeric attributes ["age", "bili", "alk", "sgot", "albu", "protime"]

In [47]:
from sklearn.preprocessing import StandardScaler

In [48]:
#num_cols = ["age", "bili", "alk", "sgot", "albu", "protime"]
scaler = StandardScaler()

scaler.fit(X_train.loc[:,num_cols])

# scale on train
X_train.loc[:,num_cols] = scaler.transform(X_train.loc[:,num_cols])
#X_train[num_cols] = scaler.transform(X_train[num_cols])

# scale on test
X_test.loc[:,num_cols] = scaler.transform(X_test.loc[:,num_cols])

METODE KLASIFIKASI  SVM

In [49]:
from sklearn.svm import SVC

In [50]:
# Create a SVC classifier using a linear kernel
linear_svm = SVC(kernel='linear', C=1, random_state=0)
# Train the classifier
linear_svm.fit(X=X_train, y= y_train)

SVC(C=1, kernel='linear', random_state=0)

In [51]:
## Predict
train_predictions = linear_svm.predict(X_train)
test_predictions = linear_svm.predict(X_test)

### Train data accuracy
from sklearn.metrics import accuracy_score,f1_score,confusion_matrix

print("TRAIN Conf Matrix : \n", confusion_matrix(y_train, train_predictions))
print("\nTRAIN DATA ACCURACY",accuracy_score(y_train,train_predictions))
print("\nTrain data f1-score for class '1'",f1_score(y_train,train_predictions,pos_label=1))
print("\nTrain data f1-score for class '2'",f1_score(y_train,train_predictions,pos_label=2))

### Test data accuracy
print("\n\n--------------------------------------\n\n")

print("TEST Conf Matrix : \n", confusion_matrix(y_test, test_predictions))
print("\nTEST DATA ACCURACY",accuracy_score(y_test,test_predictions))
print("\nTest data f1-score for class '1'",f1_score(y_test,test_predictions,pos_label=1))
print("\nTest data f1-score for class '2'",f1_score(y_test,test_predictions,pos_label=2))

TRAIN Conf Matrix : 
 [[17  9]
 [ 4 94]]

TRAIN DATA ACCURACY 0.8951612903225806

Train data f1-score for class '1' 0.723404255319149

Train data f1-score for class '2' 0.9353233830845771


--------------------------------------


TEST Conf Matrix : 
 [[ 4  2]
 [ 1 24]]

TEST DATA ACCURACY 0.9032258064516129

Test data f1-score for class '1' 0.7272727272727273

Test data f1-score for class '2' 0.9411764705882353


In [52]:
## Create an SVC object and print it to see the arguments
svc = SVC(kernel='rbf', random_state=0, gamma=0.01, C=1)
svc

SVC(C=1, gamma=0.01, random_state=0)

In [53]:
## Train the model
svc.fit(X=X_train, y= y_train)

SVC(C=1, gamma=0.01, random_state=0)

In [54]:
## Predict
train_predictions = svc.predict(X_train)
test_predictions = svc.predict(X_test)

### Train data accuracy

print("TRAIN Conf Matrix : \n", confusion_matrix(y_train, train_predictions))
print("\nTRAIN DATA ACCURACY",accuracy_score(y_train,train_predictions))
print("\nTrain data f1-score for class '1'",f1_score(y_train,train_predictions,pos_label=1))
print("\nTrain data f1-score for class '2'",f1_score(y_train,train_predictions,pos_label=2))

### Test data accuracy
print("\n\n--------------------------------------\n\n")

print("TEST Conf Matrix : \n", confusion_matrix(y_test, test_predictions))
print("\nTEST DATA ACCURACY",accuracy_score(y_test,test_predictions))
print("\nTest data f1-score for class '1'",f1_score(y_test,test_predictions,pos_label=1))
print("\nTest data f1-score for class '2'",f1_score(y_test,test_predictions,pos_label=2))

TRAIN Conf Matrix : 
 [[ 5 21]
 [ 0 98]]

TRAIN DATA ACCURACY 0.8306451612903226

Train data f1-score for class '1' 0.3225806451612903

Train data f1-score for class '2' 0.9032258064516129


--------------------------------------


TEST Conf Matrix : 
 [[ 1  5]
 [ 0 25]]

TEST DATA ACCURACY 0.8387096774193549

Test data f1-score for class '1' 0.2857142857142857

Test data f1-score for class '2' 0.9090909090909091


SVM dengan Pencarian Grid untuk Penyetelan Paramater

In [55]:
## Use Grid Search for parameter tuning

from sklearn.model_selection import GridSearchCV

svc_grid = SVC()
 
param_grid = { 
                'C': [0.001, 0.01, 0.1, 1, 10, 100 ],
                'gamma': [0, 0.0001, 0.001, 0.01, 0.1, 1, 10, 100], 
                'kernel':['linear', 'rbf', 'poly' ]
             }

svc_cv_grid = GridSearchCV(estimator = svc_grid, param_grid = param_grid, cv = 5, verbose=3)

In [56]:
## Fit the grid search model
svc_cv_grid.fit(X=X_train, y=y_train)

Fitting 5 folds for each of 144 candidates, totalling 720 fits
[CV 1/5] END ...C=0.001, gamma=0, kernel=linear;, score=0.760 total time=   0.0s
[CV 2/5] END ...C=0.001, gamma=0, kernel=linear;, score=0.800 total time=   0.0s
[CV 3/5] END ...C=0.001, gamma=0, kernel=linear;, score=0.800 total time=   0.0s
[CV 4/5] END ...C=0.001, gamma=0, kernel=linear;, score=0.800 total time=   0.0s
[CV 5/5] END ...C=0.001, gamma=0, kernel=linear;, score=0.792 total time=   0.0s
[CV 1/5] END ......C=0.001, gamma=0, kernel=rbf;, score=0.760 total time=   0.0s
[CV 2/5] END ......C=0.001, gamma=0, kernel=rbf;, score=0.800 total time=   0.0s
[CV 3/5] END ......C=0.001, gamma=0, kernel=rbf;, score=0.800 total time=   0.0s
[CV 4/5] END ......C=0.001, gamma=0, kernel=rbf;, score=0.800 total time=   0.0s
[CV 5/5] END ......C=0.001, gamma=0, kernel=rbf;, score=0.792 total time=   0.0s
[CV 1/5] END .....C=0.001, gamma=0, kernel=poly;, score=0.760 total time=   0.0s
[CV 2/5] END .....C=0.001, gamma=0, kernel=pol

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100],
                         'gamma': [0, 0.0001, 0.001, 0.01, 0.1, 1, 10, 100],
                         'kernel': ['linear', 'rbf', 'poly']},
             verbose=3)

In [57]:
# Get the best parameters
svc_cv_grid.best_params_

{'C': 0.001, 'gamma': 1, 'kernel': 'poly'}

In [58]:
svc_best = svc_cv_grid.best_estimator_

In [59]:
## Predict
train_predictions = svc_best.predict(X_train)
test_predictions = svc_best.predict(X_test)

print("TRAIN DATA ACCURACY",accuracy_score(y_train,train_predictions))
print("\nTrain data f1-score for class '1'",f1_score(y_train,train_predictions,pos_label=1))
print("\nTrain data f1-score for class '2'",f1_score(y_train,train_predictions,pos_label=2))

### Test data accuracy
print("\n\n--------------------------------------\n\n")
print("TEST DATA ACCURACY",accuracy_score(y_test,test_predictions))
print("\nTest data f1-score for class '1'",f1_score(y_test,test_predictions,pos_label=1))
print("\nTest data f1-score for class '2'",f1_score(y_test,test_predictions,pos_label=2))

TRAIN DATA ACCURACY 0.9516129032258065

Train data f1-score for class '1' 0.8695652173913043

Train data f1-score for class '2' 0.9702970297029703


--------------------------------------


TEST DATA ACCURACY 0.8709677419354839

Test data f1-score for class '1' 0.6666666666666666

Test data f1-score for class '2' 0.92


15. Simpan model

In [60]:
import pickle

In [64]:
filename = 'model_hepatitis.sav'
pickle.dump(linear_svm, open(filename, 'wb'))